name: ci

on:
  pull_request:
    branches:
      - master
      - release-*
  push:
    tags:
      - "release-*"

jobs:
  pisa-controller:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout codes"
        uses: actions/checkout@v2
      - name: "setup go faster"
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: '1.18.1'
      - name: "unit test"
        run: "cd pisa-controller && go test ./..."
      - name: "Kaniko build"
        uses: mlycore/action-kaniko@master
        with:
          image: pisanixio/controller
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: pisa-controller/hack/Dockerfile 
          tag_with_labest: true

  pisa-proxy:
    runs-on: ubuntu-latest 
    steps:
      - name: "checkout codes"
        uses: actions/checkout@v2
      - name: "prepare rs toolchain" 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test 
      - name: "Kaniko build"
        uses: mlycore/action-kaniko@master
        with:
          image: pisanixio/proxy
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: pisa-proxy/hack/Dockerfile
          tag_with_latest: true 
